doctrine:
    dbal:
        default_connection: ddc
        connections:
            ddc:
                driver: 'postgresql'
                server_version: '12'
                url: '%env(resolve:DATABASE_URL)%'
                charset: utf8
    orm:
        default_entity_manager: ddc
        entity_managers:
            ddc:
                connection: ddc
                #auto_generate_proxy_classes: true
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    ddc:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: ddc

